puts "The students of my cohort at Makers Academy"
puts "-----------"
puts "Stephen Lloyd"
puts "Alex Peattie"
puts "vic329"
puts "Nicole Pell"
puts "Bernard Mordan"
puts "Elena Garrone"
puts "Yvette Cook"
puts "Stephen Giles"
puts "Ana Isabel Nogal"
puts "craigh44"
puts "Tim Scully"
puts "Ella SChofield"
puts "Fadie H"
puts "mala23"
puts "zrasool88"
puts "galicians"
puts "Danjo Cutler"
puts "Sardine"
puts "James Scarter"
puts "S Stevens"
puts "Schlap"
puts "Andrew Whercules"
puts "Karin Nielsen"
puts "Andrew Snead"
puts "Camilla van Klinken"

print "Overall we have "
print 24
puts " great students"
